Adjust and export interfaces
selsa-inube/inubekit-fullscreennav pull request #5
Opened 2024-03-21 22:03 UTC by JanuarAsprilla

The names of the interfaces used by the `<Fullscreennav />` component were refactored, as well as how they are exported.

2024-03-26 23:08 UTC, wfercanas requested changes
1. If you execute npm run build, there are errors. Execute the command and solve the issues.
2. Include `react-icons/md` in rollupOptions (vite.config.ts)

2024-03-26 23:08 UTC, wfercanas commented on src/FullscreenNav/index.tsx
> +interface IFullscreenNavISection {
There is no need to repeat the `I`, this can just be `IFullscreenNavSection`

Avoid the repetition in all interfaces.

Note: actually, to shorten the name, we can abbreviate with `IFNavSection`, `IFNavigation`, etc.

2024-03-26 23:08 UTC, wfercanas commented on src/FullscreenNav/index.tsx
> +interface IFullscreenNavIMenuSections {
This can be `IFNavSection`, so it looks similar to what we have in the `Nav` interfaces

2024-03-26 23:08 UTC, wfercanas commented on src/FullscreenNav/index.tsx
> +interface IFullscreenNav {
This can be IFNav

2024-03-27 12:51 UTC, JanuarAsprilla commented on src/FullscreenNav/index.tsx
> +interface IFullscreenNavISection {
solved

2024-03-27 12:51 UTC, JanuarAsprilla commented on src/FullscreenNav/index.tsx
> +interface IFullscreenNavIMenuSections {
solved

2024-03-27 12:51 UTC, JanuarAsprilla commented on src/FullscreenNav/index.tsx
> +interface IFullscreenNav {
solved

2024-04-01 16:19 UTC, wfercanas requested changes

2024-04-01 16:19 UTC, wfercanas commented on src/FullscreenNav/index.tsx
> +interface IFNavSection {
There are two `IFNavScection`, there should only be one.
Check where this `IMenuSectionsProps` was used and if needed, rename it to `IFNavMenuSection`

2024-04-01 16:19 UTC, wfercanas commented on src/FullscreenNav/index.tsx
If you try to execute `npm run build` we still have problems:
![image](https://github.com/selsa-inube/inubekit-fullscreennav/assets/36939686/faf1c3dd-f0a4-4127-a518-bebd6bbd2a0c)

2024-04-02 14:49 UTC, wfercanas commented on src/FullscreenNav/index.tsx
> +interface IFNavSection {
This adjustment is still pending.
![image](https://github.com/selsa-inube/inubekit-fullscreennav/assets/36939686/2fbc642a-8049-4a7e-a6ac-69ccf97e9ea3)

2024-04-02 22:57 UTC, merged